# site settings
title: RobCob
subtitle: Industries
email: ryan@robcob.com
description: We're currently playing around with Jekyll on Github<br /> and other geeky things.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Secret Lab
city: Bozeman
state: MT
zip_code: 59714
country: United States of America
phone: (303) 875-0754

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/in/savetheplatypi/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/savetheplatypi

# build settings
markdown: kramdown

sass:
  style: compressed
